const icons = { Home:'⌂', Dashboard:'▦', 'My Tasks':'▣', Calendar:'▦', 'Focus Timer':'◴', 'Water Tracker':'♨', Habits:'♡', Notes:'▤', Goals:'✧', Analytics:'▥', Settings:'⚙' };
const pages = Object.keys(icons);
const initialTasks = [
  {id:1, title:'Complete React Project', emoji:'💗', category:'Work', time:'10:00 AM', done:true, star:true},
  {id:2, title:'Study DSA', emoji:'📚', category:'Study', time:'01:00 PM', done:true},
  {id:3, title:'Meditation & Yoga', emoji:'🧘', category:'Health', time:'06:00 AM', done:false},
  {id:4, title:'Blog Writing', emoji:'📝', category:'Personal', time:'04:30 PM', done:false},
  {id:5, title:'Water Plants', emoji:'🌿', category:'Home', time:'07:00 PM', done:false}
];
let tasks = JSON.parse(localStorage.getItem('bliss-tasks') || 'null') || initialTasks;
let page = 'Home', water = 6, timer = 25, timerId;
let isAddTaskOpen = false;
const content = document.querySelector('#content');
const nav = document.querySelector('#nav');
const modal = document.querySelector('#modalBackdrop');
function setAddTaskOpen(open) {
  isAddTaskOpen = open;
  modal.hidden = !isAddTaskOpen;
  document.body.classList.toggle('modal-open', isAddTaskOpen);
  if (isAddTaskOpen) requestAnimationFrame(() => document.querySelector('#taskName').focus());
}

function renderNav(){ nav.innerHTML = pages.map(p=>`<button class="nav-item ${p===page?'active':''}" data-page="${p}"><i>${icons[p]}</i>${p}</button>`).join(''); }
function taskRow(t){ return `<li class="task ${t.done?'done':''}"><button class="check" data-toggle="${t.id}">${t.done?'✓':''}</button><span class="task-name">${t.emoji} ${t.title}</span><span class="pill ${t.category.toLowerCase()}">${t.category}</span><time>${t.time}</time><button class="star" data-star="${t.id}">${t.star?'★':'☆'}</button><button class="delete" aria-label="Delete task" data-delete="${t.id}">×</button></li>`; }
function prettyDate(date = new Date()) { return new Intl.DateTimeFormat('en-GB', { day:'numeric', month:'long', year:'numeric' }).format(date); }
function dashboard(){ const done=tasks.filter(t=>t.done).length; return `
  <div class="stats"><article class="stat pink"><i>▤</i><div><span>Total Tasks</span><b>${tasks.length}</b><small>All tasks</small></div><em>〽</em></article><article class="stat green"><i>✓</i><div><span>Completed</span><b>${done}</b><small>This week</small></div><em>〽</em></article><article class="stat peach"><i>⌛</i><div><span>In Progress</span><b>${tasks.length-done}</b><small>Keep going!</small></div><em>〽</em></article><article class="stat sage"><i>☆</i><div><span>Productivity</span><b>${tasks.length?Math.round(done/tasks.length*100):0}%</b><small>Great job!</small></div><em>〽</em></article></div>
  <div class="dashboard-grid"><section class="card tasks-card"><div class="card-title"><h2>🌸 Today’s Tasks</h2><button class="add-task">＋ Add Task</button></div><ul class="task-list">${tasks.map(taskRow).join('')}</ul><footer><span>✨ ${done} tasks completed</span><button data-page="My Tasks">View All Tasks →</button></footer></section>
  <section class="card calendar-card"><div class="calendar-head"><button id="previousMonth">‹</button><h3 id="calendarMonth"></h3><button id="nextMonth">›</button></div>${calendar()}<div class="events"><div><b>•</b> Team Meeting <time>10:00 AM</time></div><div><b>•</b> Project Deadline <time>04:00 PM</time></div><span>🌷</span></div></section>
  <aside class="right-cards"><section class="card clock-card"><div class="clock">◷</div><div><strong id="liveTime"></strong><p id="liveDate"></p></div><blockquote>“A calm mind brings<br/>inner strength.” <span>🌾</span></blockquote></section><section class="card water"><h3>💧 Water Tracker</h3><p>${water} / 8 Glasses</p><div class="glasses">${Array.from({length:8},(_,i)=>`<button data-water="${i+1}" class="${i<water?'filled':''}">▾</button>`).join('')}</div><div class="progress"><i style="width:${water/8*100}%"></i></div><small>${Math.round(water/8*100)}%</small></section><section class="card mood"><h3>🙂 Mood Today</h3><b>Happy</b><span>☁</span></section></aside>
  <section class="bottom-cards"><article class="card focus"><h3>⏱ Focus Timer</h3><b id="timer">${String(timer).padStart(2,'0')}:00</b><p>Pomodoro</p><button class="primary" id="startTimer">${timerId?'Pause':'Start'}</button><span>🪴</span></article><article class="card goal"><h3>🎯 Daily Goal</h3><p>Finish 5 tasks today</p><div class="progress"><i style="width:${Math.min(done/5*100,100)}%"></i></div><small>${done} / 5 completed</small><span>🪴</span></article><article class="card weather"><h3>🌤 Weather</h3><b>28°C</b><p>Partly Cloudy</p><small>New Delhi, India</small></article><article class="card note"><h3>▤ Quick Note</h3><blockquote>Don’t stop until<br/>you’re proud! 🌸</blockquote></article></section></div>
  <div class="quote-bar">♡　“Discipline today, success tomorrow.”　📚</div>`; }
let calendarDate = new Date(); calendarDate.setDate(1);
function calendar(){ const ds=['Sun','Mon','Tue','Wed','Thu','Fri','Sat']; const year=calendarDate.getFullYear(), month=calendarDate.getMonth(), first=new Date(year,month,1).getDay(), count=new Date(year,month+1,0).getDate(), prev=new Date(year,month,0).getDate(), today=new Date(); let days=ds.map(d=>`<b>${d}</b>`).join(''); for(let i=0;i<42;i++){const day=i-first+1; const isToday=day===today.getDate()&&month===today.getMonth()&&year===today.getFullYear(); let value=day<1?prev+day:day>count?day-count:day; days+=`<span class="${isToday?'today':''} ${day<1||day>count?'muted':''}">${value}</span>`} return `<div class="calendar">${days}</div>`; }
function home(){ const done=tasks.filter(t=>t.done).length; return `<section class="home-page"><div class="home-welcome"><span>🌷</span><div><p>Welcome to</p><h2>Todo-Bliss</h2><h3>Your gentle space to plan, focus, and flourish.</h3><button class="primary" data-page="Dashboard">Open my dashboard →</button></div><div class="home-art">☕<i>✦</i></div></div><div class="home-overview"><article class="card"><b>${tasks.length}</b><span>Tasks on your list</span></article><article class="card"><b>${done}</b><span>Tasks completed</span></article><article class="card"><b>${Math.round(done / Math.max(tasks.length,1)*100)}%</b><span>Your progress today</span></article></div><section class="card home-next"><div><h2>Ready for your next little win?</h2><p>Add a task when you want, or head to your dashboard first.</p></div><div class="home-buttons"><button class="add-task">＋ Add a task</button><button class="outline-btn" data-page="Dashboard">Dashboard</button></div></section></section>`; }
function generic(){ const label=page==='My Tasks'?'All Your Tasks':page; const text={Calendar:'Plan your month with intention.', 'Focus Timer':'Spend a little focused time on what matters.', 'Water Tracker':'Keep your body refreshed all day.', Habits:'Small habits create a beautiful life.', Notes:'Capture the thoughts worth keeping.', Goals:'Dream big, then take one step.', Analytics:'A gentle look at your progress.', Settings:'Personalize your Todo-Bliss space.'}[page]; const body=page==='My Tasks'?`<section class="card all-tasks"><div class="card-title"><h2>Tasks for today</h2><span>${tasks.length} tasks</span></div><ul class="task-list">${tasks.map(taskRow).join('')}</ul></section>`:page==='Calendar'?`<section class="card all-tasks full-calendar"><div class="calendar-head"><button id="previousMonth">‹</button><h2 id="calendarMonth"></h2><button id="nextMonth">›</button></div>${calendar()}<p>Today is highlighted in pink. Use the arrows to browse any month.</p></section>`:`<div class="empty-state"><div>${page==='Focus Timer'?'⏳':'🌷'}</div><h3>Your ${page.toLowerCase()} space is ready</h3><p>Everything you need is right here. Keep growing at your own pace.</p><button class="primary" data-page="Dashboard">Back to dashboard</button></div>`; return `<section class="feature-page"><div class="feature-hero"><span>${icons[page]}</span><div><h2>${label}</h2><p>${text}</p></div>${page==='My Tasks'?'<button class="add-task">＋ Add Task</button>':''}</div>${body}</section>`; }
function render(){ document.querySelector('#pageTitle').innerHTML=page==='Dashboard'?'Good morning, Pranjali! <span>🌷</span>':page==='Home'?'Welcome home, Pranjali! <span>🌷</span>':page; document.querySelector('#pageSubtitle').textContent=page==='Dashboard'?'“Small steps every day lead to big changes.”':page==='Home'?'A beautiful day starts with one small intention.':'Your calm and beautiful productivity space.'; document.querySelector('.date-chip span').innerHTML=`<b>${prettyDate()}</b><small>${new Intl.DateTimeFormat('en-US',{weekday:'long'}).format(new Date())}</small>`; renderNav(); content.innerHTML=page==='Home'?home():page==='Dashboard'?dashboard():generic(); const month=document.querySelector('#calendarMonth');if(month)month.textContent=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(calendarDate); bind(); }
function bind(){ document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;document.querySelector('#sidebar').classList.remove('open');render();}); document.querySelectorAll('.add-task').forEach(b=>b.onclick=()=>setAddTaskOpen(true)); document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{let t=tasks.find(x=>x.id==b.dataset.toggle);t.done=!t.done;save()});document.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>{let t=tasks.find(x=>x.id==b.dataset.star);t.star=!t.star;save()});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{tasks=tasks.filter(x=>x.id!=b.dataset.delete);save()});document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>{water=+b.dataset.water;render()});document.querySelector('#previousMonth')?.addEventListener('click',()=>{calendarDate.setMonth(calendarDate.getMonth()-1);render()});document.querySelector('#nextMonth')?.addEventListener('click',()=>{calendarDate.setMonth(calendarDate.getMonth()+1);render()});const now=new Date(), time=document.querySelector('#liveTime'), date=document.querySelector('#liveDate');if(time)time.textContent=now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});if(date)date.innerHTML=`${now.toLocaleDateString('en-US',{weekday:'long'})}<br/>${prettyDate(now)}`;const start=document.querySelector('#startTimer');if(start)start.onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;render()}else {timerId=setInterval(()=>{if(timer>0){timer--;document.querySelector('#timer').textContent=String(timer).padStart(2,'0')+':00'}else{clearInterval(timerId);timerId=null;render()}},60000);render()}}; }
function save(){localStorage.setItem('bliss-tasks',JSON.stringify(tasks));render();}
// Shared feature data for the existing vanilla dashboard.
let theme=localStorage.getItem('bliss-theme')||'light';
let habits=JSON.parse(localStorage.getItem('bliss-habits')||'null')||[{id:1,name:'Morning stretch',streak:6,done:false},{id:2,name:'Read 20 minutes',streak:12,done:true}];
let notes=JSON.parse(localStorage.getItem('bliss-notes')||'null')||[];
let goals=JSON.parse(localStorage.getItem('bliss-goals')||'null')||[{id:1,title:'Build a consistent study habit',progress:60,deadline:'30 Jul'}];
let waterHistory=JSON.parse(localStorage.getItem('bliss-water-history')||'[]');
function persist(key,value){localStorage.setItem(key,JSON.stringify(value));}
function applyTheme(){document.documentElement.dataset.theme=theme;document.querySelectorAll('.circle-btn')[0]?.setAttribute('aria-label',theme==='dark'?'Switch to light mode':'Switch to dark mode');}
function sectionHead(title,copy,action=''){return `<section class="feature-page"><div class="feature-hero"><span>✦</span><div><h2>${title}</h2><p>${copy}</p></div>${action}</div>`;}
home = function(){const done=tasks.filter(t=>t.done).length;return `<section class="home-page"><div class="home-welcome"><span>🌷</span><div><p>Welcome to</p><h2>Todo-Bliss</h2><h3>Your gentle space to plan, focus, and flourish.</h3><div class="home-buttons"><button class="primary" data-page="Dashboard">Open my dashboard →</button><button class="outline-btn add-task">＋ Quick add</button></div></div><div class="home-art">☕<i>✦</i></div></div><div class="home-overview"><article class="card"><b>${tasks.length}</b><span>Tasks on your list</span></article><article class="card"><b>${done}</b><span>Tasks completed</span></article><article class="card"><b>${Math.round(done/Math.max(tasks.length,1)*100)}%</b><span>Your progress today</span></article></div><div class="home-widgets"><section class="card widget"><h3>Today’s focus</h3><b>${tasks.find(t=>!t.done)?.title||'Enjoy your progress'}</b><button class="text-link" data-page="Focus Timer">Start a focus session →</button></section><button class="card widget calendar-link" data-page="Calendar"><h3>🗓️ Calendar</h3><b>${prettyDate()}</b><span>Open your schedule →</span></button><section class="card widget"><h3>💧 Water intake</h3><b>${water}/8 glasses</b><div class="progress"><i style="width:${water/8*100}%"></i></div></section><section class="card widget"><h3>🔥 Habit streak</h3><b>${Math.max(...habits.map(h=>h.streak))} days</b><span>Keep your rhythm going</span></section></div><section class="card home-next"><div><h2>Upcoming tasks</h2><p>${tasks.filter(t=>!t.done).slice(0,2).map(t=>t.title).join(' · ')||'All caught up!'}</p></div><button class="outline-btn" data-page="My Tasks">View all tasks</button></section></section>`;}
function taskManager(){return sectionHead('My Tasks','Search, filter and complete what matters.','<button class="add-task">＋ Add Task</button>')+`<section class="card manager"><div class="manager-tools"><input id="taskSearch" placeholder="Search tasks"/><select id="taskFilter"><option value="all">All categories</option><option>Work</option><option>Study</option><option>Health</option><option>Personal</option><option>Home</option></select><button class="outline-btn" data-action="clear-completed">Clear completed</button></div><div class="task-stats"><span>${tasks.length} total</span><span>${tasks.filter(t=>t.done).length} complete</span><span>${tasks.filter(t=>!t.done).length} pending</span></div><ul class="task-list" id="managedTasks">${tasks.map(taskRow).join('')}</ul></section></section>`;}
function calendarPage(){return sectionHead('Calendar','Click a day to plan it.','<button class="add-task">＋ Add task</button>')+`<section class="card full-calendar"><div class="calendar-head"><button id="previousMonth">‹</button><h2 id="calendarMonth"></h2><div><button id="todayMonth">Today</button><button id="nextMonth">›</button></div></div>${calendar()}<p id="calendarSelection">Select a date to view its tasks.</p></section></section>`;}
function focusPage(){return sectionHead('Focus Timer','A quiet place for your most important work.')+`<section class="card timer-page"><div class="timer-ring"><b id="focusClock">${String(timer).padStart(2,'0')}:00</b><span>Pomodoro</span></div><div class="timer-controls"><button class="primary" data-action="focus-toggle">${timerId?'Pause':'Start'}</button><button class="outline-btn" data-action="focus-reset">Reset</button></div><div class="duration-row"><button data-action="duration" data-minutes="25">25 min</button><button data-action="duration" data-minutes="5">Short break</button><button data-action="duration" data-minutes="15">Long break</button></div><p>Sessions completed today: <b id="sessionCount">0</b></p></section></section>`;}
function waterPage(){const pct=Math.round(water/8*100);return sectionHead('Water Tracker','Small sips, steady energy.')+`<section class="card tracker-page"><div class="big-number">${water}<small>/ 8 glasses</small></div><div class="progress"><i style="width:${pct}%"></i></div><p>${pct}% complete — ${water>=8?'Amazing, you reached today’s goal!':'Your body will thank you.'}</p><div class="timer-controls"><button class="primary" data-action="drink">＋ Drink water</button><button class="outline-btn" data-action="water-reset">Reset</button></div><small>Today’s history: ${waterHistory.join(', ')||'No drinks logged yet'}</small></section></section>`;}
function habitsPage(){return sectionHead('Habits','Consistency becomes a beautiful routine.','<button class="outline-btn" data-action="add-habit">＋ Add habit</button>')+`<section class="card list-page">${habits.map(h=>`<article class="list-row"><button class="check" data-action="habit-toggle" data-id="${h.id}">${h.done?'✓':''}</button><div><b>${h.name}</b><small>${h.streak} day streak</small></div><span class="heat">▮▮▮▮▯▮▮</span><button class="delete" data-action="habit-delete" data-id="${h.id}">×</button></article>`).join('')}</section></section>`;}
function notesPage(){return sectionHead('Notes','Capture thoughts before they drift away.','<button class="outline-btn" data-action="add-note">＋ New note</button>')+`<section class="notes-grid">${notes.length?notes.map(n=>`<article class="card note-card"><button class="delete" data-action="note-delete" data-id="${n.id}">×</button><textarea data-note="${n.id}" placeholder="Write a note…">${n.text}</textarea><small>Auto-saved</small></article>`).join(''):`<div class="empty-state"><div>📝</div><h3>No notes yet</h3><p>Create a note to keep your ideas close.</p></div>`}</section></section>`;}
function goalsPage(){return sectionHead('Goals','Turn your gentle intentions into milestones.','<button class="outline-btn" data-action="add-goal">＋ Add goal</button>')+`<section class="goal-grid">${goals.map(g=>`<article class="card goal-card"><h3>${g.title}</h3><p>Deadline: ${g.deadline}</p><div class="progress"><i style="width:${g.progress}%"></i></div><b>${g.progress}% complete</b><button class="text-link" data-action="goal-progress" data-id="${g.id}">Add progress +10%</button></article>`).join('')}</section></section>`;}
function analyticsPage(){const done=tasks.filter(t=>t.done).length,pct=Math.round(done/Math.max(tasks.length,1)*100);return sectionHead('Analytics','A kind, clear view of your progress.')+`<section class="analytics-grid"><article class="card metric"><span>Productivity score</span><b>${pct}%</b></article><article class="card metric"><span>Focus time</span><b>${Math.max(0,25-timer)} min</b></article><article class="card metric"><span>Water goal</span><b>${Math.round(water/8*100)}%</b></article><article class="card chart"><h3>Weekly completion</h3><div class="bars">${[35,60,45,80,55,pct,70].map((v,i)=>`<i style="height:${v}%" title="Day ${i+1}"></i>`).join('')}</div></article><article class="card chart"><h3>Category distribution</h3><p>${['Work','Study','Health','Personal','Home'].map(c=>`${c}: ${tasks.filter(t=>t.category===c).length}`).join(' · ')}</p></article></section></section>`;}
function settingsPage(){return sectionHead('Settings','Personalize your Todo-Bliss space.')+`<section class="card settings-page"><label>Display theme <select id="themeSelect"><option value="light">Light mode</option><option value="dark">Dark mode</option></select></label><label>Username <input id="profileName" value="Pranjali" /></label><div class="settings-actions"><button class="outline-btn" data-action="export">Export data</button><button class="outline-btn danger" data-action="reset-data">Reset local data</button></div><small>Your preferences are saved on this device.</small></section></section>`;}
generic = function(){const views={'My Tasks':taskManager,Calendar:calendarPage,'Focus Timer':focusPage,'Water Tracker':waterPage,Habits:habitsPage,Notes:notesPage,Goals:goalsPage,Analytics:analyticsPage,Settings:settingsPage};return views[page]?views[page]():'';}
function featureAction(e){const b=e.target.closest('[data-action]');if(!b)return;const id=+b.dataset.id,action=b.dataset.action;if(action==='clear-completed'){tasks=tasks.filter(t=>!t.done);save()}if(action==='drink'){water=Math.min(8,water+1);waterHistory.push(new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}));persist('bliss-water-history',waterHistory);render()}if(action==='water-reset'){water=0;waterHistory=[];persist('bliss-water-history',waterHistory);render()}if(action==='focus-toggle'){if(timerId){clearInterval(timerId);timerId=null;render()}else{timerId=setInterval(()=>{timer--;if(timer<=0){clearInterval(timerId);timerId=null;timer=25;alert('Focus session complete!')}render()},60000);render()}}if(action==='focus-reset'){clearInterval(timerId);timerId=null;timer=25;render()}if(action==='duration'){clearInterval(timerId);timerId=null;timer=+b.dataset.minutes;render()}if(action==='add-habit'){const name=prompt('Habit name');if(name){habits.push({id:Date.now(),name,streak:0,done:false});persist('bliss-habits',habits);render()}}if(action==='habit-toggle'){const h=habits.find(x=>x.id===id);h.done=!h.done;h.streak+=h.done?1:-1;persist('bliss-habits',habits);render()}if(action==='habit-delete'){habits=habits.filter(x=>x.id!==id);persist('bliss-habits',habits);render()}if(action==='add-note'){notes.unshift({id:Date.now(),text:''});persist('bliss-notes',notes);render()}if(action==='note-delete'){notes=notes.filter(x=>x.id!==id);persist('bliss-notes',notes);render()}if(action==='add-goal'){const title=prompt('Goal title');if(title){goals.push({id:Date.now(),title,progress:0,deadline:'No deadline'});persist('bliss-goals',goals);render()}}if(action==='goal-progress'){const g=goals.find(x=>x.id===id);g.progress=Math.min(100,g.progress+10);persist('bliss-goals',goals);render()}if(action==='export'){const data=JSON.stringify({tasks,habits,notes,goals,water},null,2);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download='todo-bliss-data.json';a.click();URL.revokeObjectURL(a.href)}if(action==='reset-data'&&confirm('Reset all Todo Bliss data stored in this browser?')){['bliss-tasks','bliss-habits','bliss-notes','bliss-goals','bliss-water-history'].forEach(k=>localStorage.removeItem(k));location.reload()}}
content.addEventListener('click',featureAction);content.addEventListener('input',e=>{if(e.target.id==='taskSearch'){const q=e.target.value.toLowerCase();document.querySelectorAll('#managedTasks .task').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q))}if(e.target.matches('[data-note]')){const n=notes.find(x=>x.id==e.target.dataset.note);n.text=e.target.value;persist('bliss-notes',notes)}});content.addEventListener('change',e=>{if(e.target.id==='themeSelect'){theme=e.target.value;localStorage.setItem('bliss-theme',theme);applyTheme()}});content.addEventListener('click',e=>{if(e.target.id==='todayMonth'){calendarDate=new Date();calendarDate.setDate(1);render()}const day=e.target.closest('.calendar span');if(day&&!day.classList.contains('muted')){const selected=document.querySelector('#calendarSelection');if(selected)selected.textContent=`${calendarDate.toLocaleString('en-US',{month:'long'})} ${day.textContent}: ${tasks.filter(t=>!t.done).length} pending task(s) — use Add task to schedule one.`}});
document.querySelectorAll('.circle-btn')[0]?.addEventListener('click',()=>{theme=theme==='dark'?'light':'dark';localStorage.setItem('bliss-theme',theme);applyTheme();});applyTheme();
document.querySelector('#mobileMenu').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#closeModal').onclick=()=>setAddTaskOpen(false);modal.onclick=e=>{if(e.target===modal)setAddTaskOpen(false)};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&isAddTaskOpen)setAddTaskOpen(false)});document.querySelector('#taskForm').onsubmit=e=>{e.preventDefault();let time=document.querySelector('#taskTime').value;let [h,m]=time.split(':').map(Number);tasks.push({id:Date.now(),title:document.querySelector('#taskName').value,emoji:'✨',category:document.querySelector('#taskCategory').value,time:`${String((h+11)%12+1).padStart(2,'0')}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`,done:false});e.target.reset();setAddTaskOpen(false);save()};setAddTaskOpen(false);render();
